apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplejava-deployment
  labels:
    app: samplejava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplejava
  template:
    metadata:
      labels:
        app: samplejava 
    spec:
      containers:
      - name: samplejava
        image: robinksk/sample-java:1
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: samplejava-service
spec:
  selector:
    app: samplejava 
  type: NodePort
  ports:
    port: 80
    targetPort: 8080
